"use client";

import { useEffect, useState, useCallback } from "react";
import Sidebar from "@/components/dashboard/Sidebar";
import { AdminJobRole, getAdminJobRoles } from "@/services/admin";

export default function AdminRolesPage() {
  const [roles, setRoles] = useState<AdminJobRole[]>([]);
  const [loading, setLoading] = useState(true);

  const loadRoles = useCallback(async () => {
    try {
      setLoading(true);
      const data = await getAdminJobRoles();
      setRoles(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => {
      loadRoles();
    }, 0);
    return () => clearTimeout(timer);
  }, [loadRoles]);

  return (
    <div className="layout-sidebar">
      <Sidebar />
      <div className="main-content">
        <div className="topbar">
          <h1 style={{ fontSize: "16px", fontWeight: "700" }}>Job Roles Directory</h1>
          <div style={{ marginLeft: "auto" }}>
            <span className="badge badge-primary">{roles.length} Roles Active</span>
          </div>
        </div>

        <div style={{ padding: "24px" }}>
          <div className="glass glow-primary" style={{ padding: "24px", borderRadius: "16px", marginBottom: "24px" }}>
            <h2 style={{ fontSize: "22px", fontWeight: "800", letterSpacing: "-0.02em", marginBottom: "4px" }}>
              AI Career Job Roles
            </h2>
            <p style={{ color: "var(--nex-text-2)", fontSize: "14px" }}>
              All career tracks generated by AI or configured by platform administrators.
            </p>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px" }}>
            {loading ? (
              <div style={{ gridColumn: "span 3", padding: "40px", textAlign: "center", color: "var(--nex-text-3)" }}>
                Loading job roles...
              </div>
            ) : roles.length === 0 ? (
              <div style={{ gridColumn: "span 3", padding: "40px", textAlign: "center", color: "var(--nex-text-3)" }}>
                No job roles created yet. Use the Admin Console to generate one with AI.
              </div>
            ) : (
              roles.map((r) => (
                <div key={r.id} className="glass glass-hover" style={{ padding: "20px", borderRadius: "14px" }}>
                  <div style={{ fontSize: "24px", marginBottom: "8px" }}>🎯</div>
                  <h3 style={{ fontSize: "16px", fontWeight: "800", marginBottom: "6px" }}>{r.name}</h3>
                  <p style={{ fontSize: "13px", color: "var(--nex-text-2)", lineHeight: "1.5", marginBottom: "14px" }}>
                    {r.description || "Comprehensive career track with automated skill proficiency benchmarks."}
                  </p>
                  <div style={{ fontSize: "11px", color: "#a5b4fc", fontWeight: "600" }}>
                    ✓ Active Role Track
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}